#!/bin/bash
MY_PATH="$(dirname -- "${BASH_SOURCE[0]}")"            # relative
MY_PATH="$(cd -- "$MY_PATH" && pwd)"

docker run -ti --rm --net=host -e DISPLAY=$DISPLAY -v $MY_PATH/Xilinx.lic:/home/ise/.Xilinx/Xilinx.lic -v /tmp/.X11-unix:/tmp/.X11-unix  -v /home/andrea:/mnt -v /home/andrea/.Xauthority:/home/ise/.Xauthority ise-14-7

# --device=/dev/bus/usb/003/009
